export interface Feature {
  id: string;
  title: string;
  image: string;
  description: string;
  link: string;
  color: string;
  features: string[];
  tag?: string;
}

export const featuresData: Feature[] = [
  {
    id: "overview",
    title: "Overview",
    image: "/home/features/overview.png",
    description: "Comprehensive dashboard with real-time insights into school operations",
    link: "http://localhost:5174/",
    color: "#8B5CF6",
    features: [
      "Real-time analytics and metrics",
      "Customizable widgets",
      "Quick access to key functions",
      "Performance tracking",
    ],
  },
  {
    id: "account",
    title: "Account",
    image: "/home/features/account.png",
    description: "Manage user profiles, permissions, and account settings",
    link: "http://localhost:5174/account",
    color: "#3B82F6",
    features: [
      "User profile management",
      "Role-based access control",
      "Security settings",
      "Activity logs",
    ],
  },
  {
    id: "subscription",
    title: "Subscription",
    image: "/home/features/subscription.png",
    description: "Handle school subscriptions, billing, and payment plans",
    link: "http://localhost:5174/subscription/invoices",
    color: "#10B981",
    features: [
      "Multiple payment options",
      "Subscription tiers",
      "Billing history",
      "Auto-renewal management",
    ],
    tag: "Premium",
  },
  {
    id: "award-category",
    title: "Award Category",
    image: "/home/features/awardCategory.png",
    description: "Create and manage various award categories for students",
    link: "http://localhost:5174/award-category",
    color: "#F59E0B",
    features: [
      "Custom award creation",
      "Category management",
      "Achievement tracking",
      "Certificate generation",
    ],
  },
  {
    id: "award",
    title: "Award",
    image: "/home/features/award.png",
    description: "Distribute awards and recognize student achievements",
    link: "http://localhost:5174/award",
    color: "#EF4444",
    features: [
      "Award distribution",
      "Student recognition",
      "Performance badges",
      "Award history",
    ],
  },
  {
    id: "departments",
    title: "Departments",
    image: "/home/features/department.png",
    description: "Organize and manage school departments efficiently",
    link: "http://localhost:5174/departments",
    color: "#6366F1",
    features: [
      "Department structure",
      "Staff assignment",
      "Resource allocation",
      "Inter-department collaboration",
    ],
  },
  {
    id: "program",
    title: "Program",
    image: "/home/features/program.png",
    description: "Create and oversee academic programs and curricula",
    link: "http://localhost:5174/program",
    color: "#EC4899",
    features: [
      "Program creation",
      "Curriculum management",
      "Course mapping",
      "Academic standards",
    ],
  },
  {
    id: "courses",
    title: "Courses",
    image: "/home/features/courses.png",
    description: "Manage all courses, schedules, and course materials",
    link: "http://localhost:5174/courses",
    color: "#14B8A6",
    features: [
      "Course catalog",
      "Enrollment management",
      "Material distribution",
      "Course prerequisites",
    ],
  },
  {
    id: "classes",
    title: "Classes",
    image: "/home/features/classes.png",
    description: "Organize classes, assign teachers, and manage student groups",
    link: "http://localhost:5174/classes",
    color: "#F97316",
    features: [
      "Class scheduling",
      "Teacher assignment",
      "Student grouping",
      "Attendance tracking",
    ],
  },
  {
    id: "sessions",
    title: "Sessions",
    image: "/home/features/sessions.png",
    description: "Manage academic sessions, terms, and school calendar",
    link: "http://localhost:5174/sessions",
    color: "#8B5CF6",
    features: [
      "Academic calendar",
      "Session planning",
      "Term management",
      "Holiday scheduling",
    ],
  },
  {
    id: "semesters",
    title: "Semesters",
    image: "/home/features/semesters.png",
    description: "Configure semester periods and academic timelines",
    link: "http://localhost:5174/semesters",
    color: "#3B82F6",
    features: [
      "Semester setup",
      "Timeline configuration",
      "Grade period management",
      "Exam scheduling",
    ],
  },
  {
    id: "users",
    title: "Users",
    image: "/home/features/users.png",
    description: "Comprehensive user management for all stakeholders",
    link: "http://localhost:5174/manage/users",
    color: "#10B981",
    features: [
      "Student management",
      "Staff directory",
      "Parent portal access",
      "User roles & permissions",
    ],
    tag: "Popular",
  },
  {
    id: "admission",
    title: "Admission",
    image: "/home/features/admission.png",
    description: "Streamline student admission and enrollment processes",
    link: "http://localhost:5174/manage/admission",
    color: "#F59E0B",
    features: [
      "Application processing",
      "Document verification",
      "Enrollment workflow",
      "Admission analytics",
    ],
  },
  {
    id: "school-fees",
    title: "School Fees",
    image: "/home/features/schoolFees.png",
    description: "Manage tuition fees, payments, and financial records",
    link: "http://localhost:5174/school-fees",
    color: "#EF4444",
    features: [
      "Fee structure setup",
      "Payment tracking",
      "Invoice generation",
      "Financial reports",
    ],
    tag: "Essential",
  },
  {
    id: "library",
    title: "Library",
    image: "/home/features/library.png",
    description: "Digital library management with book tracking and cataloging",
    link: "http://localhost:5174/elibary/resources",
    color: "#6366F1",
    features: [
      "Book catalog",
      "Borrowing system",
      "Digital resources",
      "Library analytics",
    ],
  },
  {
    id: "hostel",
    title: "Hostel",
    image: "/home/features/hostel.png",
    description: "Manage hostel accommodations and student residences",
    link: "http://localhost:5174/manage/hostel",
    color: "#EC4899",
    features: [
      "Room allocation",
      "Occupancy tracking",
      "Maintenance requests",
      "Hostel fees",
    ],
  },
  {
    id: "messages",
    title: "Messages",
    image: "/home/features/messages.png",
    description: "Internal messaging system for school communication",
    link: "http://localhost:5174/message/management",
    color: "#14B8A6",
    features: [
      "Direct messaging",
      "Group conversations",
      "Announcements",
      "Message archives",
    ],
  },
  {
    id: "documents",
    title: "Documents",
    image: "/home/features/documents.png",
    description: "Store, organize, and share school documents securely",
    link: "http://localhost:5174/documents",
    color: "#F97316",
    features: [
      "Document repository",
      "Version control",
      "Access permissions",
      "Document templates",
    ],
  },
  {
    id: "notice-board",
    title: "Notice Board",
    image: "/home/features/noticeBoard.png",
    description: "Post and manage school notices and announcements",
    link: "http://localhost:5174/noticeboard/see/notices",
    color: "#8B5CF6",
    features: [
      "Notice posting",
      "Category management",
      "Visibility control",
      "Archive system",
    ],
  },
  {
    id: "configuration",
    title: "Configuration",
    image: "/home/features/configuration.png",
    description: "System settings and school-wide configurations",
    link: "http://localhost:5174/configurations",
    color: "#3B82F6",
    features: [
      "System preferences",
      "School branding",
      "Integration settings",
      "Backup & security",
    ],
  },
];
