import {
  CardsThreeIcon,
  GraduationCapIcon,
  InvoiceIcon,
  MoneyWavyIcon,
  NotebookIcon,
  ScrollIcon,
  SquaresFourIcon,
  StudentIcon,
  UserCircleIcon,
  UsersIcon,
  MedalIcon,
  CertificateIcon,
  FoldersIcon,
  FolderIcon,
  BooksIcon,
  BuildingsIcon,
  PushPinIcon,
  FilesIcon,
  MailboxIcon,
  GearFineIcon,
} from "@phosphor-icons/react";

export const features = [
  {
    id: 'overview',
    icon: SquaresFourIcon,
    label: "Overview",
    image: '/home/hero/overview.png',
    imageb: '/home/hero/overview_b.png'
  },
  {
    id: 'account',
    icon: UserCircleIcon,
    label: "Account",
    image: '/home/hero/account.png',
    imageb: '/home/hero/account_b.png'
  },
  {
    id: 'subscription',
    icon: InvoiceIcon,
    label: "Subscription",
    image: '/home/hero/invoice.png',
    imageb: '/home/hero/invoice_b.png',
  },
  {
    id: 'awardCategory',
    icon: CardsThreeIcon,
    label: "Award Category",
    image: '/home/hero/awardCategory.png',
    imageb: '/home/hero/invoice_b.png',
  },
  {
    id: 'award',
    icon: MedalIcon,
    label: "Award",
    image: '/home/hero/award.png',
    imageb: '/home/hero/invoice_b.png',
  },
  {
    id: 'departments',
    icon: FoldersIcon,
    label: "Departments",
    image: '/home/hero/department.png',
    imageb: '/home/hero/invoice_b.png',
  },
  {
    id: 'program',
    icon: CertificateIcon,
    label: "Program",
    image: '/home/hero/program.png',
    imageb: '/home/hero/invoice_b.png',
  },
  {
    id: 'courses',
    icon: NotebookIcon,
    label: "Courses",
    image: '/home/hero/courses.png',
    imageb: '/home/hero/invoice_b.png',
  },
  {
    id: 'classes',
    icon: FolderIcon,
    label: "Classess",
    image: '/home/hero/classes.png',
    imageb: '/home/hero/invoice_b.png',
  },
  {
    id: 'sessions',
    icon: GraduationCapIcon,
    label: "Sessions",
    image: '/home/hero/sessions.png',
    imageb: '/home/hero/invoice_b.png',
  },
  {
    id: 'semesters',
    icon: ScrollIcon,
    label: "Semesters",
    image: '/home/hero/semesters.png',
    imageb: '/home/hero/invoice_b.png',
  },
  {
    id: 'users',
    icon: UsersIcon,
    label: "Users",
    image: '/home/hero/users.png',
    imageb: '/home/hero/invoice_b.png',
  },
  {
    id: 'admission',
    icon: StudentIcon,
    label: "Admission",
    image: '/home/hero/admission.png',
    imageb: '/home/hero/invoice_b.png',
  },
  {
    id: 'schoolFees',
    icon: MoneyWavyIcon,
    label: "School Fees",
    image: '/home/hero/schoolFees.png',
    imageb: '/home/hero/invoice_b.png',
  },
  {
    id: 'elibrary',
    icon: BooksIcon,
    label: "Elibary",
    image: '/home/hero/elibrary.png',
    imageb: '/home/hero/invoice_b.png',
  },
  {
    id: 'hostel',
    icon: BuildingsIcon,
    label: "Hostel",
    image: '/home/hero/hostel.png',
    imageb: '/home/hero/invoice_b.png',
  },
  {
    id: 'emailManagement',
    icon: MailboxIcon,
    label: "Messages",
    image: '/home/hero/messages.png',
    imageb: '/home/hero/messages_b.png',
  },
  {
    id: 'documents',
    icon: FilesIcon,
    label: "Documents",
    image: '/home/hero/documents.png',
    imageb: '/home/hero/invoice_b.png',
  },
  {
    id: 'noticeBoard',
    icon: PushPinIcon,
    label: "Notice Board",
    image: '/home/hero/noticeBoard.png',
    imageb: '/home/hero/invoice_b.png',
  },
  {
    id: 'configuration',
    icon: GearFineIcon,
    label: "Configuration",
    image: '/home/hero/configurations.png',
    imageb: '/home/hero/configurations_b.png',
  },
];